# permissions for end users to edit products.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: product-editor-role
rules:
- apiGroups:
  - cache.boostcd.io
  resources:
  - products
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.boostcd.io
  resources:
  - products/status
  verbs:
  - get
